services:
  # Banco de Dados do Sistema de Vagas
  db-vagas:
    image: postgres:15
    container_name: postgres_estagiovagas
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      # Mapeado para 5436 na sua máquina para evitar conflitos se a porta 5432 já estiver em uso
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_estagiovagas:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql

  # API do Sistema de Vagas
  api-vagas:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api_estagio_vagas
    ports:
      # Mapeado para 3001 na sua máquina para não conflitar com o BackEnd (api_solar)
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      # Sobrescrevemos o localhost do .env pelo nome do serviço do banco
      DB_HOST: db-vagas
    depends_on:
      db-vagas:
        condition: service_healthy

volumes:
  pgdata_estagiovagas: